services:
  # Backend Python (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: handball_backend
    environment:
      DB_NAME: Handball
      DB_USER: postgres
      DB_PASSWORD: naruto756
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      API_HOST: 0.0.0.0
      API_PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - handball_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Next.js
  frontend:
    build:
      context: ./handball-stats
      dockerfile: Dockerfile
    container_name: handball_frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000
      INTERNAL_API_URL: http://handball_backend:8000
      DATABASE_URL: postgresql://postgres:naruto756@host.docker.internal:5432/Handball?schema=public
    ports:
      - "3000:3000"
    volumes:
      - ./handball-stats:/app
      - /app/node_modules
      - /app/.next
    networks:
      - handball_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
    command: npm run dev

networks:
  handball_network:
    driver: bridge
